# Change these first
owner: today-mm # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: 2c2p Production
    url: https://pgw.2c2p.com
  - name: 2c2p Sandbox
    url: https://sandbox-pgw.2c2p.com
  - name: Wave Money Testing
    url: https://testpayments.wavemoney.io:8107
  - name: Wave Money UAT
    url: https://uatpayments.wavemoney.io:8107
  - name: Wave Money Pre Production
    url: https://preprodpayments.wavemoney.io:8107
  - name: Wave Money Production
    url: https://payments.wavemoney.io
  - name: TBS Dash
    url: https://dash.todaybooks.com.mm
  - name: TBS Site
    url: https://www.todaybooks.com.mm
  - name: TODAY Note
    url: https://note.todaybooks.com.mm
  - name: TODAY Myanmar Font Converter
    url: https://mmfontconverter.todaybooks.com.mm
  - name: TODAY Syllable
    url: https://mmsyllable.todaybooks.com.mm

assignees: # Users to assign downtime issues (optional)
  - phyozawtun

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: today-mm.js.org/uppptime/
  #apiBaseUrl: https://api.github.com
  #cname: today-mm.github.io/upptime
  baseUrl: /uppptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  #logoUrl: https://todaybooks.com.mm/assets/img/logo.png
  name: TODAY Uptime Monitor
  introTitle: "TODAY / Uptime Monitor and Status"
  introMessage: TODAY Book Store uptime monitor and status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
